package com.bawei.haoshilong_greendao.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import bean.Automation;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "AUTOMATION".
*/
public class AutomationDao extends AbstractDao<Automation, Void> {

    public static final String TABLENAME = "AUTOMATION";

    /**
     * Properties of entity Automation.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property CommodityId = new Property(0, int.class, "commodityId", false, "COMMODITY_ID");
        public final static Property CommodityName = new Property(1, String.class, "commodityName", false, "COMMODITY_NAME");
        public final static Property MasterPic = new Property(2, String.class, "masterPic", false, "MASTER_PIC");
        public final static Property Price = new Property(3, int.class, "price", false, "PRICE");
        public final static Property SaleNum = new Property(4, int.class, "saleNum", false, "SALE_NUM");
    }


    public AutomationDao(DaoConfig config) {
        super(config);
    }
    
    public AutomationDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"AUTOMATION\" (" + //
                "\"COMMODITY_ID\" INTEGER NOT NULL ," + // 0: commodityId
                "\"COMMODITY_NAME\" TEXT," + // 1: commodityName
                "\"MASTER_PIC\" TEXT," + // 2: masterPic
                "\"PRICE\" INTEGER NOT NULL ," + // 3: price
                "\"SALE_NUM\" INTEGER NOT NULL );"); // 4: saleNum
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"AUTOMATION\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Automation entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getCommodityId());
 
        String commodityName = entity.getCommodityName();
        if (commodityName != null) {
            stmt.bindString(2, commodityName);
        }
 
        String masterPic = entity.getMasterPic();
        if (masterPic != null) {
            stmt.bindString(3, masterPic);
        }
        stmt.bindLong(4, entity.getPrice());
        stmt.bindLong(5, entity.getSaleNum());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Automation entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getCommodityId());
 
        String commodityName = entity.getCommodityName();
        if (commodityName != null) {
            stmt.bindString(2, commodityName);
        }
 
        String masterPic = entity.getMasterPic();
        if (masterPic != null) {
            stmt.bindString(3, masterPic);
        }
        stmt.bindLong(4, entity.getPrice());
        stmt.bindLong(5, entity.getSaleNum());
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public Automation readEntity(Cursor cursor, int offset) {
        Automation entity = new Automation( //
            cursor.getInt(offset + 0), // commodityId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // commodityName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // masterPic
            cursor.getInt(offset + 3), // price
            cursor.getInt(offset + 4) // saleNum
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Automation entity, int offset) {
        entity.setCommodityId(cursor.getInt(offset + 0));
        entity.setCommodityName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMasterPic(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPrice(cursor.getInt(offset + 3));
        entity.setSaleNum(cursor.getInt(offset + 4));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(Automation entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(Automation entity) {
        return null;
    }

    @Override
    public boolean hasKey(Automation entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
