package com.bawei.haoshilong_greendao.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import bean.Automation;

import com.bawei.haoshilong_greendao.dao.AutomationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig automationDaoConfig;

    private final AutomationDao automationDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        automationDaoConfig = daoConfigMap.get(AutomationDao.class).clone();
        automationDaoConfig.initIdentityScope(type);

        automationDao = new AutomationDao(automationDaoConfig, this);

        registerDao(Automation.class, automationDao);
    }
    
    public void clear() {
        automationDaoConfig.clearIdentityScope();
    }

    public AutomationDao getAutomationDao() {
        return automationDao;
    }

}
